app/urls.py
from django.urls import path

from app.views import about_page, post_page, index, search_page, tag_page, author_page

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('post/<slug:slug>/', post_page, name='post_page'),
    path('tag/<slug:slug>', tag_page, name='tag_page'),
    path('author/<slug:slug>', author_page, name='author_page'),
    path('search/', search_page, name='search_page'),
    path('about/', about_page, name='about'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from email.policy import default
from enum import unique
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User 

# Create your models here.
class WebsiteMeta(models.Model):
    """Model definition for WebsiteMeta."""

    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    about = models.TextField()

    class Meta:
        """Meta definition for WebsiteMeta."""

        verbose_name = 'WebsiteMeta'
        verbose_name_plural = 'WebsiteMetas'

    def __str__(self):
        """Unicode representation of WebsiteMeta."""
        return self.title



class Profile(models.Model):
    """Model definition for Profile."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='images/', null=True, blank=True)
    slug = models.SlugField(max_length=200, unique=True)
    bio = models.CharField(max_length=200)

    class Meta:
        """Meta definition for Profile."""

        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        """Unicode representation of Profile."""
        return self.user.first_name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.user.username)
        return super(Profile, self).save(*args, **kwargs)


class Subscribe(models.Model):
    """Model definition for Subscribe."""

    email = models.EmailField(max_length=254, unique=True)
    date = models.DateField(auto_now=True, auto_now_add=False)

    class Meta:
        """Meta definition for Subscribe."""

        verbose_name = 'Subscribe'
        verbose_name_plural = 'Subscribes'

    def __str__(self):
        """Unicode representation of Subscribe."""
        return self.email


class Tag(models.Model):
    """Model definition for Tag."""

    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        """Meta definition for Tag."""

        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Tag, self).save(*args, **kwargs)


class Post(models.Model):
    """Model definition for Post."""

    title = models.CharField(max_length=200)
    content = models.TextField()
    last_updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/", height_field=None, width_field=None, max_length=None)
    views = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True, related_name='post')
    is_featured = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        """Meta definition for Post."""

        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        """Unicode representation of Post."""
        return f"{self.title}, last updated on {self.last_updated}."


class Comment(models.Model):
    """Model definition for Comment."""

    content = models.TextField()
    date = models.DateField(auto_now=True)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=254)
    website = models.CharField(max_length=200, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True, blank=True, related_name='replies')

    class Meta:
        """Meta definition for Comment."""

        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.name

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link
      rel="stylesheet"
      href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
      rel="stylesheet"
    />

    <title>
    {% block title %}
      Blog  
    {% endblock title %}
      </title> 
  </head>
  <body>
    <header>
      <div class="container container-fluid">
        <div class="logo">
          <i class="fa-brands fa-blogger"></i>
        </div>
        <div class="links">
          <a href="{% url 'app:index' %}">Home</a>
          <a href="{% url 'app:about' %}">About</a>
          <a href="">All Posts</a>
        </div>
        <div class="action-btn">
          <a href="pages/login.html"
            ><button class="btn btn-scoundary">Login</button></a
          >
          <a href="pages/signup.html">
            <button class="btn btn-primary">Sign Up</button></a
          >
          <i class="uil uil-align-center-alt menu" onclick="menu()"></i>
        </div>
      </div>
    </header>
    <main>

    {% block content %}
        
    {% endblock content %}
     
    </main>
    <footer>
      <div class="container">
        <div class="grid-4">
          <div class="logo f-logo">
            <i class="fa-brands fa-blogger"></i>
          </div>
          <div class="link">
            <h2>Quick link</h2>
            <div class="q-link">
              <a href="{% url 'app:index' %}">Home</a>
              <a href="{% url 'app:about' %}">About</a>
              <a href="#">Unsubscribe</a>
            </div>
          </div>
          <div class="link">
            <h2>Top category</h2>
            <div class="q-link">
              <a href="#">Home</a>
              <a href="#">Blog</a>
              <a href="#">Unsubscribe</a>
            </div>
          </div>
          <div class="news-signup">
            <h2>Subscribe</h2>
            <div class="newsletter">
              <form method="POST">
                <input
                  type="email"
                  name="email"
                  maxlength="100"
                  placeholder="Enter your email"
                  required=""
                  id="id_email"
                />
                <button class="btn btn-primary">Subscribe</button>
              </form>
            </div>
          </div>
        </div>
        <div class="share">
          <div class="social">
            <a href="#">
              <i class="fa-brands fa-facebook-f"></i>
            </a>
            <a href="#">
              <i class="fa-brands fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fa-brands fa-linkedin-in"></i>
            </a>
            <a href="#">
              <i class="fa-brands fa-twitter"></i>
            </a>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'url.js' %}" id="url"></script>
  </body>
</html>