app/urls.py
from django.urls import path

from app.views import about_page, post_page, index, search_page, tag_page, author_page

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('post/<slug:slug>/', post_page, name='post_page'),
    path('tag/<slug:slug>', tag_page, name='tag_page'),
    path('author/<slug:slug>', author_page, name='author_page'),
    path('search/', search_page, name='search_page'),
    path('about/', about_page, name='about'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/about.html
{% extends 'base.html' %}

{% block title %}
  Blog | About
{% endblock title %}
  
{% block content %}  
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="https://murmuring-tundra-27912.herokuapp.com/" class="learn">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>About</h1>
            </div>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        
        {% if website_info.about %}
          <p>{{ website_info.about|safe }}</p>
        {% else %}
          <p>What is Lorem Ipsum?
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#x27;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            
            Why do we use it?
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using &#x27;Content here, content here&#x27;, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for &#x27;lorem ipsum&#x27; will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
            
            
            Where does it come from?
            Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of &quot;de Finibus Bonorum et Malorum&quot; (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, &quot;Lorem ipsum dolor sit amet..&quot;, comes from a line in section 1.10.32.
            
            The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from &quot;de Finibus Bonorum et Malorum&quot; by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
        {% endif %}
      </div>
    </section>
{% endblock content %}

app/templates/app/author.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
  Blog | {{ author.user.first_name }}
{% endblock title %}

{% block content %}  
      <div class="container">
        <div class="layout">
          <!-- left layout -->
          <div class="left">
            <div class="page-top">
              <div class="top flex">
                <div class="page-name">
                  <a href="#" class="learn">
                    <span class="material-icons"> keyboard_return </span> Go
                    back
                  </a>
                  <h1>Author</h1>
                </div>
              </div>
            </div>

            <center>
              <div class="typo">
                <h1 class="title">{{ author.user.first_name }}</h1>
                <p>
                  {{ author.bio }}
                </p>
              </div>
            </center>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Top posts</h1>
                <div class="grid-2 blog">
                  <!-- card -->
                  {% include 'app/top_posts.html' %}
                  <!-- card end-->
                </div>
              </div>
            </section>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Trendy</h1>
                <div class="grid-3 blog-grid">
                  <!-- card -->
                  {% include 'app/recent_posts.html' %}
                  <!-- card end-->
                </div>
                <center>
                  <button class="btn btn-primary rounded view">
                    View more
                    <span class="material-icons"> trending_flat </span>
                  </button>
                </center>
              </div>
            </section>
          </div>
          <!-- left layout end -->

          <!-- right layout -->
          <div class="right">
            <div class="block">
              <h2 class="title2">Top Authors</h2>
              {% for author in top_authors %}
                {% if author.profile.slug != 'admin' %}
                  <div class="recent-post other-author">
                    <div class="rounded-img">
                      <img src="{{ author.profile.profile_image.url }}" alt="" />
                    </div>
                    <div class="recent-content">
                      <h3>
                        {{ author.first_name }}
                      </h3>
                      <a class="learn" href="{% url 'app:author_page' author.profile.slug %}"
                        >Learn more
                        <span class="material-icons"> trending_flat </span></a
                      >
                    </div>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
          <!-- right layout end -->
        </div>
      </div>
{% endblock content %}

app/templates/app/index.html
{% extends 'base.html' %}


{% block title %}
    Blog | Welcome
{% endblock title %}


{% block content %}
    <main class="sp">
      <div class="container">
        <center>
          <div class="search-bar">
            <a href="{% url 'app:search_page' %}"><input type="text" placeholder="Search" />
            <div class="animated-search" onclick="searchbar()">
              <i class="uil uil-search"></i>
            </div>
            </a>
          </div>
          <div class="typo">
            {% if website_info.title %}
              <h1 class="title">{{ website_info.title }}</h1>  
            {% else %}
              <h1 class="title">Website blog title</h1>
            {% endif %}
            
            {% if website_info.description %}
              <p>
                {{ website_info.description|safe }}
              </p>
            {% else %}
              <p>
                Lorem ipsum began as scrambled, nonsensical Latin derived from
                Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
              </p>
            {% endif %}
          </div>
          <div class="newsletter">
            <form method="POST">
              {% csrf_token %}
              {{ form }}
              <button class="btn btn-primary">Subscribe</button>
            </form>
          </div>
        </center>
      </div>
    </main>
    {% if featured_post %}
    <section class="sp">
      <div class="container">
        <a href="{% url 'app:post_page' featured_post.slug %}">
        <div class="grid-2">
          <div class="post-img">
            <img src="{{ featured_post.image.url }}" alt="" />
          </div>
          <div class="post-content">
            <div class="cetagory">
              <p>{{ featured_post.tags.all.0 }}</p>
            </div>
            <h1>
              {{ featured_post.title }}
            </h1>
            <p class="des">
              {{ featured_post.content|truncatechars:200|safe }}
            </p>
            <a class="learn" href="#"
              >Learn more <span class="material-icons"> trending_flat </span></a
            >
          </div>
        </div>
      </a>
      </div>
    </section>
    {% endif %}
    <section class="sp">
      <div class="container">
        <h1 class="sec-title">Top blogs</h1>
        <div class="grid-3">
            {% include 'app/top_posts.html' %}
        </div>
        <center>
          <a href=""><button class="btn btn-primary rounded view">
            View more <span class="material-icons"> trending_flat </span>
          </button></a>
        </center>
      </div>
    </section>
    <section class="sp">
      <div class="container">
        <h1 class="sec-title">New blogs</h1>
        <div class="grid-3">
          {% include 'app/recent_posts.html' %}
        </div>
        <center>
          <a href=""><button class="btn btn-primary rounded view">
            View more <span class="material-icons"> trending_flat </span>
          </button></a>
        </center>
      </div>
    </section>
{% endblock content %}
   

app/templates/app/post.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Blog | The Super Blog
{% endblock title %}
    

{% block content %} 
<div class="container">
    <div class="layout">
      <!-- left layout -->
      <div class="left">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn">
                <span class="material-icons"> keyboard_return </span> Go
                back
              </a>
              <h1>Blog</h1>
            </div>
          </div>
        </div>
  
        <center>
          <div class="typo">
            <h1 class="title blog-title">
              {{ post.title }}
            </h1>
            <div class="timeline">
              <div class="track">
                <i class="uil uil-clock"></i>
                <p class="time">{{ post.last_updated }}</p>
              </div>
              <div class="track">
                <i class="uil uil-users-alt"></i>
                <p class="view-count">{{ post.views }} view{{ post.views|pluralize }}</p>
              </div>
              <div class="track">
                <form action="" method="POST">
                  <button type="submit" class="btn btn-info">
                    <i class="uil uil-bookmark-full"></i>
                    <p class="bookmark">Bookmark</p>
                    <!-- REMOVE BOOKMARK
                      <i class="fa-solid fa-bookmark"></i> -->
                  </button>
                </form>
              </div>
            </div>
          </div>
        </center>
        <section class="mt">
          <div class="container">
            <!-- blog post -->
            <div class="blog-post">
              <div class="post-img blog-img">
                <img src="{{ post.image.url }}" alt="" />
              </div>
              <div class="blog-post-content">
                <p>
                  {{ post.content|safe }}
                </p>
                <div class="blog-tags">
                  {% for tag in post.tags.all %}
                    <a href="{% url 'app:tag_page' tag.slug %}"><div class="tag">{{ tag.name }}</div></a>
                  {% endfor %}
                </div>
                <div class="social-share">
                  <div class="reactions">
                    <div class="likes">
                      <i class="uil uil-heart"></i> <span>200</span>
                    </div>
                    <div class="total-comments">
                      <i class="uil uil-comment-alt"></i>
                      <span>10</span>
                    </div>
                  </div>
                  <div class="share">
                    <div class="social">
                      <a href="#">
                        <i class="fa-brands fa-facebook-f"></i>
                      </a>
                      <a href="#">
                        <i class="fa-brands fa-instagram"></i>
                      </a>
                      <a href="#">
                        <i class="fa-brands fa-linkedin-in"></i>
                      </a>
                      <a href="#">
                        <i class="fa-brands fa-twitter"></i>
                      </a>
                    </div>
                  </div>
                </div>
                <!-- comments -->
                {% for comment in comments %}
                <div class="user-comment">
                  <div class="author">
                    <div class="profile-pic">
                      <img src="{% static 'images/male.png' %}" alt="" />
                    </div>
                    <div class="details">
                      <p>{{ comment.name }}</p>
                      <small>{{ comment.date }}</small>
                    </div>
                  </div>
                  <div class="comment-sec-main">
                    <div class="comment-sec">
                      <div class="comment">
                        <p>
                          {{ comment.content }}
                        </p>
                      </div>
                      <div class="reply">
                        <button onclick="toggleDiv(this)">Reply</button>
                      </div>
                      <div class="comment-box" id="comment-reply-box">
                        <h3>Reply to post</h3>
                        <p>
                          Your email address will not be published. Required fields
                          are marked<span>*</span>
                        </p>
                        <form method="POST">
                          {% csrf_token %}
                          {{ form.content }}
                          <div class="grid-3">
                            <input type="hidden" name="post_id" value="{{ post.id }}">
                            <input type="hidden" name="parent" value="{{ comment.id }}">
                            {{ form.name }}
                            {{ form.email }}
                            {{ form.website }}
                          </div>
          
                          <button class="btn btn-primary rounded">
                            Post Reply
                          </button>
                        </form>
                      </div>  
                    </div>
                    <div class="public-reply">
                      {% for reply in comment.replies.all %}
                      <div class="author">
                        <div class="profile-pic">
                          <img src="{% static 'images/male.png' %}" alt="" />
                        </div>
                        <div class="details">
                          <p>{{ reply.name }}</p>
                          <small>{{ reply.date }}</small>
                        </div>
                      </div>
                      <div class="comment">
                        <p>
                          {{ reply.content }}
                        </p>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                {% endfor %}
                <!-- user comment end -->
              </div>
            </div>
            <div class="comment-box">
              <h3>Leave a new comment to this post</h3>
              <p>
                Your email address will not be published. Required fields
                are marked<span>*</span>
              </p>
              <form action="" method='post'>
                {% csrf_token %}
                {{ form.content }}
                <div class="grid-3">
                  <input type="hidden" name="post_id" value="{{ post.id }}">
                  {{ form.name }}
                  {{ form.email }}
                  {{ form.website }}
                </div>
                <button class="btn btn-primary rounded">
                  Post comment
                </button>
              </form>
            </div>
          </div>
        </section>
      </div>
      <!-- left layout end -->

      <!-- right layout -->
      <div class="right">
        <div class="block">
          <h2 class="title2">Most recent</h2>
          <div class="recent-post">
            <div class="rounded-img">
              <img src="../images/post.png" alt="" />
            </div>
            <div class="recent-content">
              <h3>
                A blog title and other stuffs will add here, also we can
                incluse.
              </h3>
              <a class="learn" href="#"
                >Learn more
                <span class="material-icons"> trending_flat </span></a
              >
            </div>
          </div>
          <div class="recent-post">
            <div class="rounded-img">
              <img src="../images/post.png" alt="" />
            </div>
            <div class="recent-content">
              <h3>
                A blog title and other stuffs will add here, also we can
                incluse.
              </h3>
              <a class="learn" href="#"
                >Learn more
                <span class="material-icons"> trending_flat </span></a
              >
            </div>
          </div>
          <div class="recent-post">
            <div class="rounded-img">
              <img src="../images/post.png" alt="" />
            </div>
            <div class="recent-content">
              <h3>
                A blog title and other stuffs will add here, also we can
                incluse.
              </h3>
              <a class="learn" href="#"
                >Learn more
                <span class="material-icons"> trending_flat </span></a
              >
            </div>
          </div>
        </div>

        <div class="block r-blog">
          <h2 class="title2">Related Blogs</h2>
          <!-- card -->
          <a href="#">
            <div class="card">
              <div class="post-img">
                <img src="../images/post.png" alt="" />
                <div class="tag">Tag name</div>
              </div>
              <div class="card-content">
                <h3>
                  A blog title and other stuffs will add here, also we can
                  include.
                </h3>
                <div class="author">
                  <div class="profile-pic">
                    <img src="../images/author.svg" alt="" />
                  </div>
                  <div class="details">
                    <p>Author name</p>
                    <small>June 20, 2022</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          <!-- card end-->

          <!-- card -->
          <a href="#">
            <div class="card">
              <div class="post-img">
                <img src="../images/post.png" alt="" />
                <div class="tag">Tag name</div>
              </div>
              <div class="card-content">
                <h3>
                  A blog title and other stuffs will add here, also we can
                  include.
                </h3>
                <div class="author">
                  <div class="profile-pic">
                    <img src="../images/author.svg" alt="" />
                  </div>
                  <div class="details">
                    <p>Author name</p>
                    <small>June 20, 2022</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          <!-- card end-->
        </div>
        <div class="block">
          <h2 class="title2">Top category</h2>
          <div class="card">
            <h3>
              A blog title and other stuffs will add here, lso we can
              incluse.
            </h3>
            <p>
              Lorem ipsum began as scrambled, nonsensical Latin derived from
              Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
            </p>
            <a class="learn" href="#"
              >Learn more
              <span class="material-icons"> trending_flat </span></a
            >
          </div>
          <div class="card">
            <h3>
              A blog title and other stuffs will add here, lso we can
              incluse.
            </h3>
            <p>
              Lorem ipsum began as scrambled, nonsensical Latin derived from
              Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
            </p>
            <a class="learn" href="#"
              >Learn more
              <span class="material-icons"> trending_flat </span></a
            >
          </div>
          <div class="card">
            <h3>
              A blog title and other stuffs will add here, lso we can
              incluse.
            </h3>
            <p>
              Lorem ipsum began as scrambled, nonsensical Latin derived from
              Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
            </p>
            <a class="learn" href="#"
              >Learn more
              <span class="material-icons"> trending_flat </span></a
            >
          </div>
        </div>
        <div class="block">
          <h2 class="title2">Top Tags</h2>
          <div class="blog-tags">
            <div class="tag">Tag</div>
            <div class="tag">Tag content</div>
            <div class="tag">Tag</div>
            <div class="tag">Tag content</div>
            <div class="tag">Tag content</div>
            <div class="tag">Tag</div>
            <div class="tag">Tag content</div>
            <div class="tag">Tag content</div>
            <div class="tag">Tag</div>
            <div class="tag">Tag content</div>
            <div class="tag">Tag</div>
          </div>
        </div>
      </div>
      <!-- right layout end -->
    </div>
</div>  
{% endblock content %}   

 

app/templates/app/recent_posts.html
{% for post in recent_posts %}
    <!-- card -->
    <a href="{% url 'app:post_page' post.slug %}">
        <div class="card">
        <div class="post-img">
            <img src="{{ post.image.url }}" alt="" />
            <div class="tag">{{ post.tags.all.0 }}</div>
        </div>
        <div class="card-content">
            <h3>
            {{ post.title }}
            </h3>
            <div class="author">
            <div class="profile-pic">
                <img src="{{ post.author.profile.profile_image.url }}" alt="" />
            </div>
            <div class="details">
                <p>{{ post.author.profile.user.first_name }}</p>
                <small>{{ post.last_updated|date }}</small>
            </div>
            </div>
        </div>
        </div>
    </a>
    <!-- card end-->
{% endfor %}

app/templates/app/search.html
{% extends 'base.html' %}

{% block title %}
  Blog | Search  
{% endblock title %}
  

{% block content %} 
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="#" class="learn">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>Search</h1>
            </div>
            <form class="search-bar s-active" method='GET'>
              <input type="text" value="{{ search_query }}" placeholder="Search" name='q'/>
              <button type='submit'><div class="animated-search">
                <i class="uil uil-search"></i>
                </div>
              </button>
            </form>
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
        <div class="grid">
          {% for post in posts %}
            <!-- card -->
            <a href="{% url 'app:post_page' post.slug %}">
              <div class="card">
                <div class="post-img">
                  <img src="{{ post.image.url }}" alt="" />
                  <div class="tag">{{ post.tags.all.0 }}</div>
                </div>
                <div class="card-content">
                  <h3>
                    {{ post.title }}
                  </h3>
                  <div class="author">
                    <div class="profile-pic">
                      <img src="{{ post.author.profile.profile_image.url }}" alt="" />
                    </div>
                    <div class="details">
                      <p>{{ post.author.first_name }}</p>
                      <small>{{ post.last_updated|date }}</small>
                    </div>
                  </div>
                </div>
              </div>
            </a>
            <!-- card end-->
          {% endfor %}
        </div>
      </div>
    </section>
{% endblock content %}

app/templates/app/tag.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ post.name }}
{% endblock title %}
  

{% block content %}
      <div class="container">
        <div class="layout">
          <!-- left layout -->
          <div class="left">
            <div class="page-top">
              <div class="top flex">
                <div class="page-name">
                  <a href="#" class="learn">
                    <span class="material-icons"> keyboard_return </span> Go
                    back
                  </a>
                  <h1>Tag</h1>
                </div>
              </div>
            </div>

            <center>
              <div class="typo">
                <h1 class="title">{{ post_name }}</h1>
                <p>
                  Lorem ipsum began as scrambled, nonsensical Latin derived from
                  Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
                </p>
              </div>
            </center>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Top posts</h1>
                <div class="grid-2 blog">
                  {% include 'app/top_posts.html' %}
                </div>
              </div>
            </section>
            <section class="sp">
              <div class="container">
                <h1 class="sec-title">Recent posts</h1>
                <div class="grid-3 blog-grid">
                  <!-- card -->
                  {% include 'app/recent_posts.html' %}
                  <!-- card end-->
                </div>
                <center>
                  <button class="btn btn-primary rounded view">
                    View more
                    <span class="material-icons"> trending_flat </span>
                  </button>
                </center>
              </div>
            </section>
          </div>
          <!-- left layout end -->

          <!-- right layout -->
          <div class="right">
            <div class="block">
              <h2 class="title2">Other Tags</h2>
              <div class="blog-tags">
                {% for tag in other_tags %}
                  {% if tag.slug != slug %}
                    <a href="{% url 'app:tag_page' tag.slug %}">
                      <div class="tag">{{ tag.name }}</div>
                    </a>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
          <!-- right layout end -->
        </div>
      </div>
{% endblock content %}

app/templates/app/top_posts.html
{% for post in top_posts %}  
    <!-- card -->
    <a href="{% url 'app:post_page' post.slug %}">
        <div class="card">
        <div class="post-img">
            <img src="{{ post.image.url }}" alt="" />
            <div class="tag">{{ post.tags.all.0 }}</div>
        </div>
        <div class="card-content">
            <h3>
            {{ post.title }}
            </h3>
            <div class="author">
            <div class="profile-pic">
                <img src="{{ post.author.profile.profile_image.url }}" alt="" />
            </div>
            <div class="details">
                <p>{{ post.author.profile.user.first_name }}</p>
                <small>{{ post.last_updated|date }}</small>
            </div>
            </div>
        </div>
        </div>
    </a>
    <!-- card end-->            
{% endfor %}